#!/usr/bin/env python
from __future__ import print_function

import configurator
import yaml


if __name__ == '__main__':
    parser = configurator.ConfigurationParser()
    data = parser.parse_args()
    print(yaml.dump(data, allow_unicode=True, default_flow_style=False))
